### PR TITLE
Minor update to dev branch

### PR DESCRIPTION
**Pull request by istruble**
I cleaned up a typo in the test_settings template file and started to break the tests up a little bit.  The typo fix is in the first commit and is the only obvious have-to-fix item in this pull request.

A conditional was added to skip a TestSuite if the api credentials are blank.

Most of the tests with `for header_auth in (True, False)` are broken into two tests to make it easier to know if the test was failing with header_auth=True or header_auth=False.  A few of the broken out tests are also intentionally skipped because it is not clear that they are all actually correct things to be testing.  More than anything else, the skipped tests will make us think about the validity of each test.

I could not get any of the RDIO tests to pass but I did make an at risk change and moved two lines into setUp().

Looking forward to seeing how things behave after `requests` gets that [alter-body-after-hooks (requests #445)](https://github.com/kennethreitz/requests/issues/445) update that you offered.

Best,
Ian

### CODE REVIEW

**Comment by maraujop** [comment]
Hi Ian,

Thanks for your pull request. 

First, you are right about the typo in `test_settings.py.template`

No worries about the rdio tests. Rdio tests are failing at the moment, raising 411s, this is due to a bug in requests, that i reported months ago:
https://github.com/kennethreitz/requests/issues/356

This issue was closed as a duplicate of 223 (Which hasn't been fixed):
https://github.com/kennethreitz/requests/issues/223 

Before seeing your pull request, I threw a change to testing system:
 https://github.com/maraujop/requests-oauth/commit/20a7a8aeda05f403996852b3261894432aec4b56

If you agree with me. I would like not to have repeated tests, as they are hard to maintain. While updating a test variable in order to run specific authentication tests, is a piece of cake. 

I will cherry-pick your typo fix and your preliminary testing condition checking. What do you think?

Cheers,
Miguel

**Comment by istruble** [comment]
I actually broke the tests out because it was difficult to figure out which
of the versions of the tests were failing.  During my first pass on the
tests, I threw in an `import pdb; pdb.set_trace()` into the tests to help
me see what was failing before breaking the tests out a bit.

Being able to quickly figure out exactly which test case is failing goes a
long way to me as an outsider trying to help test the project.  Others
might appreciate it as well.  Yes, it does cost time and effort to
 maintain the tests. If it means it makes it easier to figure out that the
header_auth=True case is failing but the header_auth=False is passing in a
given test then it is time well spent.

In my experience, you spend way more time testing and debugging than you
care to admit.  So I would vote avoid the `for header_auth in XXX:` logic
and give each test a name.  Even through the for loop syntax looks like
less work, it turns out to be more when you are in deep debug mode.

There is my suggestion and reasoning but this is your project so go with
what feels best to you.  It is a great module and I plan on using it at
work if requests gets updated and allows you to push out a few bug fixes.

Best,
Ian

Oh, please cherry pick away!  Maybe just merge from the second [1](https://github.com/istruble/requests-oauth/commit/8f9ac0ee895c55650701ce548fca1bcd2ec3d651) of the
three commits in my pull request.

On Sat, Mar 17, 2012 at 10:01 AM, Miguel Araujo <
reply@reply.github.com

**Comment by maraujop** [comment]
Hi Ian,

After consideration, I've decided you are right about splitting tests. I've merged your branch into `dev`. I had to remove the `skipIf` calls for compatibility with older Python interpreters.

Sorry to take so long to do so. But I guess since I cannot release a new version of the application, till hook system gets fixed in requests, I'm quite apathetic with this.

Thanks for your contribution, I'm adding you to AUTHORS.

Cheers,
Miguel

**Comment by istruble** [comment]
Yes, mart-e, you are definitely correct.  We want TWITTER_CONSUMER_{KEY,SECRET}.  My update replaced one typo with another.  Sloppy on my part.  I just looked and both you and anisse pointed out the same thing.  Pulled in the commit from your patch-1 branch and added you to AUTHORS.  Will open up another pull request with your fix.

**Comment by maraujop** [comment]
Sorry Martin, you are right,

I've asked Ian to submit that pull request, so I can fix it, he's merged your commit in.

**Pull request merged**
